openapi: "3.0.3"
info:
  title: Vinci Stock eXchange accounts service
  version: "1.0"
servers:
  - url: http://localhost:9001
    description: Development Server
paths:
  /accounts/{username}:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
        example: "Alice007"
        description: The account username

    post:
      summary: Create a new account
      requestBody:
        description: Account to create
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/new_account'

      responses:
        200:
          description: Account created
        400:
          description: Username does not match body or is invalid
        409:
          description: Username already taken

    get:
      summary: Get an account
      responses:
        200:
          description: Account found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/account'
        404:
          description: Account not found
    put:
      summary: Update an account
      requestBody:
        description: Account to update
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/new_account'
      responses:
        200:
          description: Account updated
        400:
          description: Username does not match body or is invalid
        404:
          description: Account not found

    delete:
      summary: Delete an account
      responses:
        200:
          description: Account deleted
        404:
          description: Account not found


  /accounts/{username}/add-cash/{value}:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
        example: "Alice007"
        description: The account username
      - name: value
        in: path
        required: true
        schema:
          type: number
          format: double
        example: 1000.0
        description: The amount of cash to add
    patch:
      summary: Add cash to the account
      responses:
        200:
          description: Cash added
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/account'
        400:
          description: Value is invalid
        404:
          description: Account not found


  /accounts/{username}/remove-cash/{value}:
    parameters:
      - name: username
        in: path
        required: true
        schema:
          type: string
        example: "Alice007"
        description: The account username
      - name: value
        in: path
        required: true
        schema:
          type: number
          format: double
        example: 1000.0
        description: The amount of cash to remove
    patch:
      summary: Remove cash from the account
      responses:
        200:
          description: Cash removed
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/account'
        400:
          description: Value is invalid
        404:
          description: Account not found

  /accounts/{username}/total-value:
    get:
      summary: Get the total value of an account
      responses:
        200:
          description: Total value found
          content:
            'application/json':
              schema:
                type: number
                format: double
                example: 1000.0
        404:
          description: Account not found

components:
  schemas:
    account:
      type: object
      properties:
        username:
          type: string
        firstname:
          type: string
        cash:
          type: number
          format: double
      example:
        username: "Alice007"
        firstname: "Alice"
        lastname: "Wonderland"
        cash: 0.0

    new_account:
      type: object
      properties:
        username:
          type: string
        firstname:
          type: string
        lastname:
          type: string

      example:
        username: "Alice007"
        firstname: "Alice"
        lastname: "Wonderland"
