openapi: 3.0.3
info:
  title: Vinci Stock eXchange Orders Service
  description: This is the Vinci Stock eXchange Orders Service
  version: "1.0"
servers:
  - url: https://localhost:9003
    description: Local development server
paths:
  /orders:
    post:
      summary: Create a new order
      requestBody:
        description: Order to be created
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/orderToCreate"
      responses:
        200:
            description: Order created
            content:
                application/json:
                schema:
                    $ref: "#/components/schemas/order"
        400:
            description: Invalid input, object invalid
        404:
            description: Order not found


components:
  schemas:
    orderToCreate:
      type: object
      properties:
        owner:
          type: string
        stock-name:
            type: string
        quantity:
            type: number
            format: integer
        side:
            type: string
            enum: [BUY, SELL]
        type:
            type: string
            enum: [MARKET, LIMIT]
        price:
            type: number
            format: float
    order:
      type: object
      properties:
        owner:
          type: string
        stock-name:
            type: string
        quantity:
            type: number
            format: integer
        //todo: add properties from entity


  
