openapi: 3.0.3
info:
  title: Vinci Stock Exchange Prices Services
  description: Microservice handling the prices of the stocks
  version: 1.0.0
servers:
  - url: 'http://localhost:9005'
    description: Development server
paths:

  /prices:

    get:
      summary: Read all prices
      responses:
        200:
          description: Returned list of prices
          content:
            'application/json':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/price'


  /prices/{stock-name}:
    parameters:
      - name: stock-name
        in: path
        required: true
        description: Name of the stock
        schema:
          type: string

    get:
      summary: Read price by stock name
      responses:
        200:
          description: Returned price
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/price'
        404:
          description: Price not found

    patch:
      summary: Actualize prices by stock name
      responses:
        200:
          description: Price updated
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/price'
        404:
          description: No stock found


  /prices/{stock-name}/{last-price}:
    parameters:
      - name: stock-name
        in: path
        required: true
        description: Name of the stock
        schema:
          type: string
      - name: last-price
        in: path
        required: true
        description: Value of the last price
        schema:
          type: number
          format: double
    patch:
      summary: Actualize last price by stock name
      responses:
        200:
          description: Price updated
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/price'
        404:
          description: No stock found


components:
  schemas:
    price:
      type: object
      properties:
        stockName:
          type: string
        buyPrice:
          type: number
          format: double
        sellPrice:
          type: number
          format: double
        lastPrice:
          type: number
          format: double
