openapi: 3.0.3
info:
  title: Vinci Stock eXchange stock service
  version: 1.0.0
servers:
  - url: http://localhost:9002
    description: Development server
paths:
  /stocks/{owner}:
    get:
      summary: get the owner stocks
      parameters:
        - name: owner
          in: path
          required: true
          description: owner username
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stock'
        400:
          description: Bad Request
        401:
          description: User unauthorized to do this action

  /stocks/{owner}/{stockname}/add/{quantity}:
    patch:
      summary: add the asked quantity of the wanted stock to the owner
      parameters:
        - name: owner
          in: path
          required: true
          description: owner username
          schema:
            type: string
        - name: stockname
          in: path
          required: true
          description: stock name
          schema:
            type: string
        - name: quantity
          in: path
          required: true
          description: quantity of stock wanted
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stock'
        400:
          description: Bad Request
        401:
          description: User unauthorized to do this action
        404:
          description: Ressource not found

  /stocks/{owner}/{stockname}/remove/{quantity}:
    patch:
      summary: remove the asked quantity of the wanted stock to the owner
      parameters:
        - name: owner
          in: path
          required: true
          description: owner username
          schema:
            type: string
        - name: stockname
          in: path
          required: true
          description: stock name
          schema:
            type: string
        - name: quantity
          in: path
          required: true
          description: quantity of stock wanted
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/stock'
        400:
          description: Bad Request
        401:
          description: Unauthorized
        404:
          description: Ressource not found

components:
  schemas:
    stock:
      type: object
      properties:
        owner:
          type: string
        stock_name:
          type: string
        quantity:
          type: number
